import type { Member, TimeSlot, Team } from '@/types/team';

export const mockMembers: Member[] = [
  { id: 1, name: '김민수', status: '온라인' },
  { id: 2, name: '박지영', status: '바쁨' },
  { id: 3, name: '강민재', status: '바쁨' },
  { id: 4, name: '송하늘', status: '온라인' },
  { id: 5, name: '이도윤', status: '온라인' },
  { id: 6, name: '최서연', status: '바쁨' },
  { id: 7, name: '정우진', status: '온라인' },
  { id: 8, name: '한지민', status: '바쁨' },
];

export const mockTimeSlots: TimeSlot[] = [
  {
    id: 1,
    day: '9월 8일 월요일',
    time: '10:00-12:00',
    participants: '8/8명 참석 가능',
    tag: '최적',
  },
  {
    id: 2,
    day: '9월 9일 화요일',
    time: '14:00-16:00',
    participants: '8/8명 참석 가능',
    tag: '최적',
  },
  {
    id: 3,
    day: '9월 10일 수요일',
    time: '09:00-11:00',
    participants: '7/8명 참석 가능',
    tag: '좋음',
  },
  {
    id: 4,
    day: '9월 11일 목요일',
    time: '15:00-17:00',
    participants: '6/8명 참석 가능',
    tag: '좋음',
  },
];

export const mockTeams: Team[] = [
  {
    code: 'WEB2024',
    name: '웹개발 팀플',
    members: ['푸름이', '김철수', '이영희', '박민수'],
    meetings: 2,
    color: 'blue',
  },
  {
    code: 'AI2024',
    name: 'AI 공모전',
    members: ['푸름이', '최지훈', '정수연'],
    meetings: 1,
    color: 'emerald',
  },
  {
    code: 'STUDY2024',
    name: '알고리즘 스터디',
    members: ['푸름이', '한지민'],
    meetings: 0,
    color: 'amber',
  },
  {
    code: 'DESIGN2024',
    name: 'UI/UX 디자인 팀',
    members: ['푸름이', '김민지', '박서준', '이하늘'],
    meetings: 3,
    color: 'purple',
  },
  {
    code: 'MOBILE2024',
    name: '모바일 앱 개발',
    members: ['푸름이', '최동욱', '정예린'],
    meetings: 1,
    color: 'green',
  },
  {
    code: 'BACKEND2024',
    name: '백엔드 개발팀',
    members: ['푸름이', '김개발', '이서버'],
    meetings: 2,
    color: 'red',
  },
  {
    code: 'DATA2024',
    name: '데이터 분석팀',
    members: ['푸름이', '박데이터', '최분석', '김통계'],
    meetings: 1,
    color: 'indigo',
  },
  {
    code: 'GAME2024',
    name: '게임 개발팀',
    members: ['푸름이', '이게임', '박유니티'],
    meetings: 4,
    color: 'pink',
  },
  {
    code: 'SECURITY2024',
    name: '보안 연구팀',
    members: ['푸름이', '김보안'],
    meetings: 0,
    color: 'gray',
  },
  {
    code: 'BLOCKCHAIN2024',
    name: '블록체인 스터디',
    members: ['푸름이', '이블록', '박체인', '김코인', '최디파이'],
    meetings: 2,
    color: 'yellow',
  },
  {
    code: 'DEVOPS2024',
    name: 'DevOps 팀',
    members: ['푸름이', '김도커', '이쿠버'],
    meetings: 1,
    color: 'teal',
  },
  {
    code: 'QA2024',
    name: '품질보증팀',
    members: ['푸름이', '박테스트', '이품질', '김검증'],
    meetings: 3,
    color: 'orange',
  },
  {
    code: 'RESEARCH2024',
    name: '기술 연구팀',
    members: ['푸름이', '최연구'],
    meetings: 0,
    color: 'cyan',
  },
  {
    code: 'STARTUP2024',
    name: '창업 동아리',
    members: ['푸름이', '김창업', '이스타트', '박업체'],
    meetings: 5,
    color: 'lime',
  },
  {
    code: 'MENTOR2024',
    name: '멘토링팀',
    members: ['푸름이', '선배님', '김멘토'],
    meetings: 1,
    color: 'violet',
  },
  {
    code: 'CLOUD2024',
    name: '클라우드 팀',
    members: ['푸름이', '김AWS', '이Azure'],
    meetings: 2,
    color: 'blue',
  },
  {
    code: 'IOT2024',
    name: 'IoT 개발팀',
    members: ['푸름이', '박센서', '이아두이노'],
    meetings: 1,
    color: 'green',
  },
  {
    code: 'VR2024',
    name: 'VR/AR 팀',
    members: ['푸름이', '김가상', '이현실', '박메타'],
    meetings: 3,
    color: 'purple',
  },
  {
    code: 'FINTECH2024',
    name: '핀테크 팀',
    members: ['푸름이', '김금융', '이결제'],
    meetings: 2,
    color: 'emerald',
  },
  {
    code: 'ECOMMERCE2024',
    name: '이커머스 팀',
    members: ['푸름이', '박쇼핑', '이마켓', '김커머스', '최판매'],
    meetings: 4,
    color: 'amber',
  },
  {
    code: 'SOCIAL2024',
    name: '소셜미디어 팀',
    meetings: 1,
    members: ['푸름이', '김소셜', '이미디어'],
    color: 'pink',
  },
  {
    code: 'HEALTH2024',
    name: '헬스케어 팀',
    members: ['푸름이', '박건강', '이의료'],
    meetings: 0,
    color: 'red',
  },
  {
    code: 'EDU2024',
    name: '에듀테크 팀',
    members: ['푸름이', '김교육', '이학습', '박온라인'],
    meetings: 2,
    color: 'indigo',
  },
  {
    code: 'TRAVEL2024',
    name: '여행앱 팀',
    members: ['푸름이', '김여행', '이관광'],
    meetings: 1,
    color: 'teal',
  },
  {
    code: 'FOOD2024',
    name: '푸드테크 팀',
    members: ['푸름이', '박음식', '이배달', '김레시피'],
    meetings: 3,
    color: 'orange',
  },
];
